language: perl
perl:
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
  - 5.8
script:
  - prove -lrs t
  - if perl -M5.016 -e1; then (dzil authordeps --missing | cpanm -nq || { cat ~/.cpanm/build.log ; false ; }) fi
  - if perl -M5.016 -e1; then (dzil listdeps --author --missing | cpanm -nq || { cat ~/.cpanm/build.log ; false ; }) fi
  - if perl -M5.016 -e1; then (dzil test --all) fi
